tasks:
  build-job:
    #runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        # mvn clean verify sonar:sonar \
        #     -Dsonar.projectKey=school \
        #     -Dsonar.host.url=http://13.127.0.77:9000 \
        #     -Dsonar.login=sqp_5c2d732bd9ce22435aca0fa4b2613488c2be7d16
        mvn clean package                  # build the package 
        ls -a
        ls target 
        kubectl get nodes 
    - docker/build:
       image: razoropsrepocode/wisdom-school       # build the image with Dockerfile
       push: true                           # push image to docker hub repository Which is integrated  
       tags: ["latest"]
