tasks:
  build-job:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package                  # build the package 
        ls -a
        ls target 
    - docker/build:
       image: razoropsrepocode/wisdom-school       # build the image with Dockerfile
       push: true                           # push image to docker hub repository Which is integrated  
       tags: ["latest"]
