tasks:
  build-job:
  pyhton-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
       sonar-scanner \
        -Dsonar.projectKey=python-app \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://65.2.9.93:9000 \
        -Dsonar.login=1bf58d2febae4a22923ce11d284d4d86f48d3f3f
    next-job:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package                  # build the package 
        ls -a
        ls target 
    - docker/build:
       image: razoropsrepocode/wisdom-school       # build the image with Dockerfile
       push: true                           # push image to docker hub repository Which is integrated  
       tags: ["latest"]
