tasks:
  hello-job:
   #runner: razorci/openjdk:11-buster
    steps:
    - git --version
    - checkout
    - cache/pull:
        key: maven-repo-{{ checksum "pom.xml" }}
        fallback_key: maven-repo-
        
    - run: mvn clean package
    - docker/build:
       image: shivaladdu/newsh      # build the image with Dockerfile
       push: true                           # push image to docker hub repository Which is integrated  
       tags: ["latest"]
    - reports/junit: 
      - target/surefire-reports/TEST-*.xml
