---
steps:
  - name: gcr.io/cloud-builders/git
    id: get-commit-id
    entrypoint: bash
    args:
      - -c
      - |
        echo "Source code is already cloned by Cloud Build."
        _COMMIT_ID=$(git rev-parse --short=5 HEAD)
        echo "Commit ID: $_COMMIT_ID"
        echo "$_COMMIT_ID" > /workspace/commit_id
  - name: gcr.io/cloud-builders/mvn
    args:
      - clean
      - package
  - name: gcr.io/cloud-builders/gcloud
    args:
      - auth
      - configure-docker
      - asia-south1-docker.pkg.dev
  - name: gcr.io/cloud-builders/docker
    id: build-image
    entrypoint: bash
    args:
      - -c
      - |
        _COMMIT_ID=$(cat /workspace/commit_id)
        docker build \
          -t asia-south1-docker.pkg.dev/$_PROJECT_ID/newschool/school:$_COMMIT_ID \
          .
  - name: gcr.io/cloud-builders/docker
    id: push-image
    entrypoint: bash
    args:
      - -c
      - >
        _COMMIT_ID=$(cat /workspace/commit_id)


        docker push asia-south1-docker.pkg.dev/$_PROJECT_ID/newschool/school:$_COMMIT_ID
logsBucket: gs://school-build-logs
options:
  logging: GCS_ONLY
