steps:
  # Step 1: Get the commit ID
  - name: gcr.io/cloud-builders/git
    id: "get-commit-id"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Source code is already cloned by Cloud Build."
        git fetch --unshallow
        echo "short commit is $(git rev-parse --short=6 HEAD)"
        newcommit='$(git rev-parse --short=6 HEAD)'
        echo "Commit ID is: $newcommit"
        #echo "$_COMMIT_ID" > /workspace/commit_id

#   # Step 2: Set up JDK (for Maven)
#   - name: gcr.io/cloud-builders/mvn
#     args:
#       - clean
#       - package

#   # Step 3: Authenticate to Google Cloud
#   - name: gcr.io/cloud-builders/gcloud
#     args:
#       - auth
#       - configure-docker
#       - asia-south1-docker.pkg.dev

#   # Step 4: Build the Docker image with commit ID as tag
#   - name: gcr.io/cloud-builders/docker
#     id: "build-image"
#     entrypoint: "bash"
#     args:
#       - "-c"
#       - |
#         _COMMIT_ID=$(cat /workspace/commit_id)
#         ['docker build -t asia-south1-docker.pkg.dev/$_PROJECT_ID/newschool:$_COMMIT_ID', '.']

#   # Step 5: Push the Docker image with commit ID as tag
#   - name: gcr.io/cloud-builders/docker
#     id: "push-image"
#     entrypoint: "bash"
#     args:
#       - "-c"
#       - |
#         _COMMIT_ID=$(cat /workspace/commit_id)
#         docker push asia-south1-docker.pkg.dev/$_PROJECT_ID/newschool:$_COMMIT_ID

logsBucket: gs://school-build-logs

options:
  logging: GCS_ONLY
