steps:
  - name: gcr.io/cloud-builders/git
    id: "fetch-version"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        _LAST_TAG=$(git describe --tags --abbrev=0 || echo "v1.0")
        NEW_VERSION=$(echo $_LAST_TAG | awk -F'.' '{print $1"."$2+1}')
        echo "Using version: $NEW_VERSION"

logsBucket: gs://school-build-logs  # Option 1 (Use GCS logs)

# options:
#   logging: CLOUD_LOGGING_ONLY  # Option 2 (Use Cloud Logging)
