steps:
  # Step 1: Retrieve the latest version
  - name: gcr.io/cloud-builders/gcloud
    id: "get-version"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -f version.txt ]; then
          newversion=$(cat version.txt)
        else
          newversion="v1.0"
        fi
        echo "Previous Version: $newversion"
        
        # Increment version (v1.0 → v1.1, v1.1 → v1.2, etc.)
        newmajor=$(echo $newversion | cut -d'.' -f1 | sed 's/v//')
        newminor=$(echo $newversion | cut -d'.' -f2)
        _NEWnewversion="v${newmajor}.$((newminor + 1))"
        
        echo "New Version: $_NEWnewversion"
        echo $_NEWnewversion > version.txt
        cat version.txt  # Print new version

logsBucket: gs://school-build-logs  # Option 1 (Use GCS logs)

# options:
#   logging: CLOUD_LOGGING_ONLY  # Option 2 (Use Cloud Logging)
